package com.pandagallery.app.data.story

import com.pandagallery.app.data.local.dao.MediaDao
import com.pandagallery.app.data.local.dao.StoryDao
import com.pandagallery.app.data.local.entity.StoryClipEntity
import com.pandagallery.app.data.local.entity.StoryEntity
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.withContext
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Background engine for assembling Samsung Gallery-style auto-generated stories and highlight reels.
 */
@Singleton
class StoryEngine @Inject constructor(
    private val storyDao: StoryDao,
) {
    private val transitions = listOf("CROSSFADE", "ZOOM_IN", "PAN_LEFT", "FADE_TO_BLACK")

    fun observeAllStories(): Flow<List<StoryEntity>> = storyDao.observeAllStories()

    fun observeStoryClips(storyId: Long): Flow<List<StoryClipEntity>> = storyDao.observeClipsForStory(storyId)

    suspend fun getClipsForStory(storyId: Long): List<StoryClipEntity> = withContext(Dispatchers.IO) {
        storyDao.getClipsForStory(storyId)
    }

    suspend fun createHighlightReel(
        title: String,
        mediaIds: List<Long>,
        templateName: String = "Classic",
        clipDurationMs: Long = 3000L,
    ): Long = withContext(Dispatchers.IO) {
        if (mediaIds.isEmpty()) return@withContext 0L

        val coverId = mediaIds.first()
        val totalDurationSeconds = ((mediaIds.size * clipDurationMs) / 1000L).toInt().coerceAtLeast(1)

        val story = StoryEntity(
            title = title,
            subtitle = "${mediaIds.size} moments",
            coverMediaId = coverId,
            durationSeconds = totalDurationSeconds,
            templateName = templateName,
            isAutoGenerated = false
        )
        val storyId = storyDao.insertStory(story)

        val clips = mediaIds.mapIndexed { index, mediaId ->
            StoryClipEntity(
                storyId = storyId,
                clipOrder = index,
                mediaId = mediaId,
                durationMs = clipDurationMs,
                transitionEffect = transitions[index % transitions.size],
                caption = null
            )
        }
        storyDao.insertClips(clips)
        storyId
    }

    suspend fun deleteStory(storyId: Long) = withContext(Dispatchers.IO) {
        storyDao.deleteClipsForStory(storyId)
        storyDao.deleteStoryById(storyId)
    }
}
