package com.pandagallery.app.data.local.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Entity representing an auto-generated or custom story/highlight reel.
 */
@Entity(
    tableName = "stories",
    indices = [Index(value = ["createdAt"])]
)
data class StoryEntity(
    @PrimaryKey(autoGenerate = true)
    val id: Long = 0L,
    val title: String,
    val subtitle: String? = null,
    val coverMediaId: Long,
    val createdAt: Long = System.currentTimeMillis(),
    val durationSeconds: Int = 30,
    val musicTrackUri: String? = null,
    val templateName: String = "Classic", // Classic, Nostalgia, Energetic, Minimal
    val isAutoGenerated: Boolean = true
)

/**
 * Clips belonging to a story reel.
 */
@Entity(
    tableName = "story_clips",
    primaryKeys = ["storyId", "clipOrder"],
    indices = [Index(value = ["storyId"]), Index(value = ["mediaId"])]
)
data class StoryClipEntity(
    val storyId: Long,
    val clipOrder: Int,
    val mediaId: Long,
    val durationMs: Long = 3000L,
    val transitionEffect: String = "CROSSFADE", // CROSSFADE, ZOOM_IN, PAN_LEFT, FADE_TO_BLACK
    val caption: String? = null
)
